### ISSUE TITLE
make internet-based tests optional

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#104]
see

https://anonscm.debian.org/git/python-modules/packages/python-molotov.git/commit/?id=1369f5c515f0757bab355a670f9bcf851b0930d9

cc @onovy

**Comment by onovy** [comment]
hi,

first of all, thanks for taking care of downstream :).

I think simplest solution is to move 'TRAVIS' env check few lines up.

Please don't try to autodetect if internet is accessible, because checking if internet works is internet access, which is forbidden when building Debian package. Or autodetect it but allow override with env.

**Comment by tarekziade** [comment]
I want to test those in TRAVIS though. Maybe I can look at a specific env variable.

would PYBUILD_SYSTEM work?

**Comment by onovy** [comment]
please use new env variable, for example 'NO_INTERNET', or something like this.

 PYBUILD_SYSTEM is not good idea, because we can change build system in future.

Thanks.
