### ISSUE TITLE
[Blocking] Following error is seen with molotov 2.3 on pip install molotov

### ISSUE THREAD

**Issue by madhav-pai** [loads/molotov#138]
ERROR: Could not find a version that satisfies the requirement aiomeasures (from molotov) (from versions: none)
ERROR: No matching distribution found for aiomeasures (from molotov)

Molotov - 2.3
aiomeasures package cannot be located on the pypi server

**Comment by nikitanovosibirsk** [comment]
Package aiomeasures is missing https://pypi.org/project/aiomeasures/  🤔

Workaround:
```
pip3 install molotov --no-dependencies
pip3 install aiohttp aiodogstatsd multiprocessing_on_dill git+https://github.com/cookkkie/aiomeasures@v0.5.14
```

**Comment by n1ngu** [comment]
Has it been removed from the package index? Holy cow! @cookkkie are you the owner of the PyPI project?

That git repo has been stale for the past 6 years anyway, so probably it'd be wise to either 
- drop that dependency altogether, along with the features it supported
- vendor it
- fork it and maintain it

For a short-term mitigation, maybe https://pypi.org/project/aiomeasures-fork/ could be considered as a drop-in replacement?

This affects all releases since ad6d85c50c792957af68473d72fd72a0398f14b3 . That is from 1.4 to 2.3. Right now a `pip install molotov` instruction will resolve the 1.3 release as the latest installable version.

**Comment by madhav-pai** [comment]
can a release be churned without this dependency ? if there is no likelihood of molotov using this under the hood

**Comment by tarekziade** [comment]
Released at https://pypi.org/project/molotov/2.4/

Thanks for letting me know
