### ISSUE TITLE
add template files to quickstart

### ISSUE THREAD

**Issue by rpappalax** [loads/molotov#49]
boilerplate Makefile and Dockerfile.  

NOTE: Eventually we may also want to combine molotov.json and loads-broker.tpl into one config file as well.

**Comment by tarekziade** [comment]
There's already a Makefile, see https://github.com/loads/molotov/blob/master/molotov/quickstart/Makefile

also, as we discussed earlier, the docker image should be on its own, see https://github.com/loads/molotov/issues/22

**Comment by rpappalax** [comment]
@tarekziade thanks, Tarek. i probably should have waited to file this issue, because i'd like to revisit some of the options in the Makefile together with the whole workflow and configs for molotov and loads-broker.  
In regards to the docker image, i did assume it would be in dockerhub, but if the Dockerfile for that image doesn't reside here, not sure where we'd put it?  up on dockerhub together with the image?

**Comment by tarekziade** [comment]
> In regards to the docker image, i did assume it would be in dockerhub, but if the Dockerfile for that image doesn't reside here, not sure where we'd put it? up on dockerhub together with the image?

The plan as I understood it would be to:

- have a single image for all the load tests we do 
- maintain that image in a dedicated repo (like loads/molotov-docker) so that's where the Dockerfile is
- use it for running any molotov-based test in loads-broker

If there's a super specific thing to do in the docker image for a given test, the test can simply use the molotov image as a basis and tweak it.

Happy to do that work by creating the molotov-docker repo and pushing the image to docker hub - as long as that works with you.

**Comment by tarekziade** [comment]
see https://github.com/loads/molotov-docker

**Comment by rpappalax** [comment]
+1
